---
title: "Falsification"
author: "Peiyuan Zhu"
date: "2023-12-07"
output: rmarkdown::html_vignette
# output: word_document
vignette: >
  %\VignetteIndexEntry{Falsification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(dst) 
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The theory of belief functions can be used to falsify possible hypotheses via counterfactuals. Here's an example.

```{r}
a <- 1e-5
fr <- 2
qt <- 0.25
v <- c("a","b","c","d")
x<-bca(matrix(c(0,1,0,0,1,1,1,1), nrow=2, byrow=TRUE), m=c(a,1-a), cnames=v)
y<-bca(matrix(c(0,1,0,0,1,1,1,1), nrow=2, byrow=TRUE), m=c(a,1-a), cnames=v)
z<-bca(matrix(c(1,0,1,0,1,1,1,1), nrow=2, byrow=TRUE), m=c(a*fr,1-a*fr), cnames=v)
w1<-dsrwonLogsumpexp(x, y, use_ssnames = TRUE)
bcaPrint(w1)
w2<-dsrwonLogsumpexp(w1, z, use_ssnames = TRUE)
bcaPrint(w2)
o<-bca(matrix(c(0,0,1,1,1,1,1,1), nrow=2, byrow=TRUE), m=c(a*fr,1-a*fr), cnames=v)
w3<-dsrwonLogsumpexp(w2, o, use_ssnames = TRUE)
bcaPrint(w3)

q<-quantile(w2$spec[,2], qt, type=1)
wtq<-bcaTrunc(w2, q, TRUE)
bcaPrint(wtq)
t <- a/2
w2t<-bcaTrunc(w2, t, TRUE)
bcaPrint(w2t)
```
