---
title: "PJM_example_DSC"
author: "Peiyuan Zhu"
date: "2024-05-13"
output: rmarkdown::html_vignette
# output: word_document
vignette: >
  %\VignetteIndexEntry{PJM_example_DSC}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
devtools::load_all(".") # only used in place of dst when testing with R-devel
# library(dst) 
knitr::opts_chunk$set(echo = TRUE)
```

Now we code the PJM example in DS-ECP. 

```{r}
tt_SSMw1 <- matrix(c(1,0,0,1,1,1), nrow = 3, ncol = 2, byrow = TRUE)
m_DSMw1 <- matrix(c(0.4,0.6,0), nrow = 3, ncol = 1)
cnames_SSMw1 <- c("w1y", "w1n") 
varnames_SSMw1 <- "w1"
idvar_SSMw1 <- 1
DSMw1 <- bca(tt_SSMw1, m_DSMw1, cnames = cnames_SSMw1, idvar = idvar_SSMw1, varnames = varnames_SSMw1)
```

```{r}
tt_SSMw2 <- matrix(c(1,0,0,1,1,1), nrow = 3, ncol = 2, byrow = TRUE)
m_DSMw2 <- matrix(c(0.3,0.7,0), nrow = 3, ncol = 1)
cnames_SSMw2 <- c("w2y", "w2n") 
varnames_SSMw2 <- "w2"
idvar_SSMw2 <- 2
DSMw2 <- bca(tt_SSMw2, m_DSMw2, cnames = cnames_SSMw2, idvar = idvar_SSMw2, varnames = varnames_SSMw2)
```

```{r}
tt_SSMA <- matrix(c(1,1), nrow = 1, ncol = 2, byrow = TRUE)
m_DSMA <- matrix(c(1), nrow = 1, ncol = 1)
cnames_SSMA <- c("Ay", "An") 
varnames_SSMA <- "A"
idvar_SSMA <- 3
DSMA <- bca(tt_SSMA, m_DSMA, cnames = cnames_SSMA, idvar = idvar_SSMA, varnames = varnames_SSMA)
```

```{r}
tt_SSMC <- matrix(c(1,1), nrow = 1, ncol = 2, byrow = TRUE)
m_DSMC <- matrix(c(1), nrow = 1, ncol = 1)
cnames_SSMC <- c("Cy", "Cn") 
varnames_SSMC <- "C"
idvar_SSMC <- 4
DSMC <- bca(tt_SSMC, m_DSMC, cnames = cnames_SSMC, idvar = idvar_SSMC, varnames = varnames_SSMC)
```

```{r}
tt_SSMP <- matrix(c(1,1), nrow = 1, ncol = 2, byrow = TRUE)
m_DSMP <- matrix(c(1), nrow = 1, ncol = 1)
cnames_SSMP <- c("Py", "Pn") 
varnames_SSMP <- "P"
idvar_SSMP <- 5
DSMP <- bca(tt_SSMP, m_DSMP, cnames = cnames_SSMP, idvar = idvar_SSMP, varnames = varnames_SSMP)
```

```{r}
tt_SSMR1 <- matrix(c(1,0,1,0,1,0,0,1,
                     1,0,0,1,1,0,0,1,
                     1,0,1,0,0,1,0,1,
                     
                     0,1,1,0,0,1,0,1,
                     0,1,0,1,1,0,0,1,
                     0,1,0,1,0,1,1,0,
                     0,1,1,0,1,0,0,1,
                     0,1,0,1,1,0,1,0,
                     0,1,1,0,0,1,1,0,
                     0,1,1,0,1,0,1,0,
                     
                     1,1,1,1,1,1,1,1), nrow = 3 + 7 + 1, ncol = 8, byrow = TRUE, dimnames = list(NULL, c("w1y","w1n","Ay","An","Cy","Cn","Py","Pn")))
spec_DSMR1 <- matrix(c(1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,0), nrow = 3 + 7 + 1, ncol = 2)
infovar_SSMR1 <- matrix(c(1,3,4,5,2,2,2,2), nrow = 4, ncol = 2)
varnames_SSMR1 <- c("w1", "A", "C", "P")
relnb_SSMR1 <- 1
DSMR1 <- bcaRel(tt_SSMR1, spec_DSMR1, infovar_SSMR1, varnames_SSMR1, relnb_SSMR1)
```

```{r}
tt_SSMR2 <- matrix(c(1,0,0,1,1,0,0,1,
                     1,0,0,1,0,1,1,0,
                     1,0,0,1,1,0,1,0,
                     
                     0,1,1,0,0,1,0,1,
                     0,1,0,1,1,0,0,1,
                     0,1,0,1,0,1,1,0,
                     0,1,1,0,1,0,0,1,
                     0,1,0,1,1,0,1,0,
                     0,1,1,0,0,1,1,0,
                     0,1,1,0,1,0,1,0,
                     
                     1,1,1,1,1,1,1,1), nrow = 3 + 7 + 1, ncol = 8, byrow = TRUE, dimnames = list(NULL, c("w2y","w2n","Ay","An","Cy","Cn","Py","Pn")))
spec_DSMR2 <- matrix(c(1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,0), nrow = 3 + 7 + 1, ncol = 2)
infovar_SSMR2 <- matrix(c(2,3,4,5,2,2,2,2), nrow = 4, ncol = 2)
varnames_SSMR2 <- c("w2", "A", "C", "P")
relnb_SSMR2 <- 2
DSMR2 <- bcaRel(tt_SSMR2, spec_DSMR2, infovar_SSMR2, varnames_SSMR2, relnb_SSMR2)
```

Now we apply Dempster-Shafer calculus.

```{r}
DSMw1_uproj <- extmin(DSMw1,DSMR1)
DSM1 <- dsrwon(DSMw1_uproj,DSMR1)
DSM1_dproj <- elim(DSM1,1)
bcaPrint(DSM1_dproj)
```

```{r}
DSMw2_uproj <- extmin(DSMw2,DSMR2)
DSM2 <- dsrwon(DSMw2_uproj,DSMR2)
DSM2_dproj <- elim(DSM2,2)
bcaPrint(DSM2_dproj)
```

```{r}
DSM3 <- dsrwon(DSM1_dproj,DSM2_dproj)
bcaPrint(DSM3)
```

```{r}
DSM3_elim_A<-elim(DSM3,3)
DSM3_elim_AP<-elim(DSM3_elim_A,5)
bcaPrint(DSM3_elim_AP)
```