# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Augment list of binary vectors with closure elements
#' 
#' @param ttxl list of binary vectors
#' @export
NULL

closure <- function(ttxl) {
    .Call(`_dst_closure`, ttxl)
}

